package enums;

public enum Category {
  SERVICOS_DIGITAIS,
  PERFUMARIA_E_COSMETICOS,
  ALIMENTOS_E_BEBIDAS,
  CASA_E_DECORACAO,
  SAUDE_E_BEMESTAR,
  UTENSILIOS_DOMESTICOS,
  MIDIA,
  PRODUTOS_PARA_PETS,
  EQUIPAMENTOS_DE_ESCRITORIO
}